/**
 * Pipeline Template Utility Tests
 */

import { describe, it, expect } from "vitest";
import {
  expandTemplate,
  getBranchPrefix,
  buildCommitMessage,
  buildPRTitle,
  buildPRBody,
  buildTemplateVars,
} from "../../../src/shared/pipeline-template.js";
import type { PipelineConfig, PipelineTemplateVars } from "../../../src/shared/types.js";

const defaultVars: PipelineTemplateVars = {
  task: "Add login feature",
  commission: "implement-login",
  branch: "atelier/implement-login",
  date: "2026-03-30",
};

describe("expandTemplate", () => {
  it("should replace all known template variables", () => {
    const template = "{{task}} for {{commission}} on {{branch}} at {{date}}";
    const result = expandTemplate(template, defaultVars);
    expect(result).toBe(
      "Add login feature for implement-login on atelier/implement-login at 2026-03-30",
    );
  });

  it("should leave unknown variables untouched", () => {
    const template = "{{task}} with {{unknown}}";
    const result = expandTemplate(template, defaultVars);
    expect(result).toBe("Add login feature with {{unknown}}");
  });

  it("should return the template as-is if no variables are present", () => {
    const template = "No variables here";
    const result = expandTemplate(template, defaultVars);
    expect(result).toBe("No variables here");
  });

  it("should handle multiple occurrences of the same variable", () => {
    const template = "{{task}} - {{task}}";
    const result = expandTemplate(template, defaultVars);
    expect(result).toBe("Add login feature - Add login feature");
  });

  it("should handle empty template string", () => {
    const result = expandTemplate("", defaultVars);
    expect(result).toBe("");
  });
});

describe("getBranchPrefix", () => {
  it("should return default prefix when config is undefined", () => {
    expect(getBranchPrefix(undefined)).toBe("atelier/");
  });

  it("should return default prefix when branchPrefix is not set", () => {
    expect(getBranchPrefix({})).toBe("atelier/");
  });

  it("should return configured prefix", () => {
    const config: PipelineConfig = { branchPrefix: "myapp/" };
    expect(getBranchPrefix(config)).toBe("myapp/");
  });
});

describe("buildCommitMessage", () => {
  it("should use default template when config is undefined", () => {
    const result = buildCommitMessage(defaultVars);
    expect(result).toBe("atelier: implement-login (Add login feature)");
  });

  it("should use configured template", () => {
    const config: PipelineConfig = {
      commitMessageTemplate: "feat: {{task}} [{{commission}}]",
    };
    const result = buildCommitMessage(defaultVars, config);
    expect(result).toBe("feat: Add login feature [implement-login]");
  });

  it("should use default template when commitMessageTemplate is not set", () => {
    const config: PipelineConfig = {};
    const result = buildCommitMessage(defaultVars, config);
    expect(result).toBe("atelier: implement-login (Add login feature)");
  });
});

describe("buildPRTitle", () => {
  it("should use default template when config is undefined", () => {
    const result = buildPRTitle(defaultVars);
    expect(result).toBe("atelier: implement-login (Add login feature)");
  });

  it("should use configured template", () => {
    const config: PipelineConfig = {
      prTitleTemplate: "[ATELIER] {{task}}",
    };
    const result = buildPRTitle(defaultVars, config);
    expect(result).toBe("[ATELIER] Add login feature");
  });

  it("should truncate titles longer than 100 characters", () => {
    const longTask: PipelineTemplateVars = {
      ...defaultVars,
      task: "A".repeat(120),
    };
    const config: PipelineConfig = {
      prTitleTemplate: "{{task}}",
    };
    const result = buildPRTitle(longTask, config);
    expect(result.length).toBe(103); // 100 + "..."
    expect(result).toMatch(/\.\.\.$/);
  });
});

describe("buildPRBody", () => {
  it("should return null when config is undefined", () => {
    const result = buildPRBody(defaultVars);
    expect(result).toBeNull();
  });

  it("should return null when prBodyTemplate is not set", () => {
    const config: PipelineConfig = {};
    const result = buildPRBody(defaultVars, config);
    expect(result).toBeNull();
  });

  it("should expand configured template", () => {
    const config: PipelineConfig = {
      prBodyTemplate: `## Summary\n{{task}}\n\n## Generated by ATELIER\nCommission: {{commission}}`,
    };
    const result = buildPRBody(defaultVars, config);
    expect(result).toBe(
      "## Summary\nAdd login feature\n\n## Generated by ATELIER\nCommission: implement-login",
    );
  });

  it("should include date and branch variables", () => {
    const config: PipelineConfig = {
      prBodyTemplate: "Branch: {{branch}}, Date: {{date}}",
    };
    const result = buildPRBody(defaultVars, config);
    expect(result).toBe("Branch: atelier/implement-login, Date: 2026-03-30");
  });
});

describe("buildTemplateVars", () => {
  it("should use task when provided", () => {
    const vars = buildTemplateVars({
      task: "My task",
      commission: "my-commission",
      branch: "atelier/my-branch",
    });
    expect(vars.task).toBe("My task");
    expect(vars.commission).toBe("my-commission");
    expect(vars.branch).toBe("atelier/my-branch");
    // date is dynamic, just check format
    expect(vars.date).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });

  it("should fall back to commission name when task is not provided", () => {
    const vars = buildTemplateVars({
      commission: "my-commission",
      branch: "atelier/my-branch",
    });
    expect(vars.task).toBe("my-commission");
  });
});
